version: '3.8'

services:
  db:
    container_name: exchanger_db_dev
    image: postgres:14
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - ${DB_PORT}
    command: -p ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: unless-stopped
    volumes:
      - exchanger_db_volume_dev:/var/lib/postgresql/data
    networks:
      - exchanger_network_dev

  pgAdmin:
    container_name: exchanger_db_pgadmin4_dev
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_EXTERNAL_PORT}:${PGADMIN_INTERNAL_PORT}
    attach: false
    networks:
      - exchanger_network_dev

volumes:
  exchanger_db_volume_dev:
    name: exchanger_db_volume_dev

networks:
  exchanger_network_dev:
    name: exchanger_network_dev
