version: '3.8'
services:
  trontools:
    container_name: trontools
    image: trontools/quickstart
    ports:
      - 9090:9090
    environment:
      - defaultBalance=100000
      - showQueryString=true
      - showBody=true
      - formatJson=true
