version: '3.8'

services:
  api:
    container_name: exchanger_app
    user: root
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: always

  db:
    container_name: exchanger_db
    image: postgres:14
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    volumes:
      - exchanger_db_volume:/var/lib/postgresql/data

  pgAdmin:
    container_name: exchanger_db_pgadmin4
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_EXTERNAL_PORT}:${PGADMIN_INTERNAL_PORT}
    attach: false

volumes:
  exchanger_db_volume:
    name: exchanger_db_volume
